Improve error handling in generatepdf workflow
Added error handling for tlmgr update commands in the PDF generation workflow.

diff --git a/.github/workflows/generatepdf.yaml b/.github/workflows/generatepdf.yaml
--- a/.github/workflows/generatepdf.yaml
+++ b/.github/workflows/generatepdf.yaml
@@ -62,12 +62,20 @@ jobs:
           if [ $? -ne 0 ]; then
             tlmgr option repository https://mirror.math.princeton.edu/pub/CTAN/systems/texlive/tlnet
             tlmgr update --self
+            if [ $? -ne 0 ]; then
+              echo "Update Self Error'd with: $?"
+              exit 1
+            fi
           fi
           tlmgr option repository https://mirror.ctan.org/systems/texlive/tlnet
           tlmgr update --all
           if [ $? -ne 0 ]; then
             tlmgr option repository https://mirror.math.princeton.edu/pub/CTAN/systems/texlive/tlnet
             tlmgr update --all
+            if [ $? -ne 0 ]; then
+              echo "Update All Error'd with: $?"
+              exit 1
+            fi
           fi
         post_compile: "latexmk -c"
 
